goSSRA.Registration/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;


namespace goSSRA.Registration.Models
{

    public class Enrollment
    {
        public int EnrollmentID { get; set; }

        [Display(Name = "Enrollers Name")]
        public string EnrollersName { get; set; }

        public int AthleteID { get; set; }
        public Athlete Athlete { get; set; }

        public int ProgramID { get; set; }
        public Program Program { get; set; }

        [Display(Name = "Enrollment Date")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime EnrollmentDate { get; set; }

        [Display(Name = "Payment Email")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\+-]+(\\.[a-zA-Z0-9_\\+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.([a-zA-Z]{2,4})$", ErrorMessage = "Invalid email address")]
        public String PaymentEmail { get; set; }

        // used in payment options screens
        public Int32? Amount { get; set; }

        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Paid To Date")]
        public double PaidToDate { get; set; }

        [Display(Name = "Unpaid Amount")]
        public double UnpaidAmount { get; set; }

        // boolean to inform user if they paid or not
        public bool Paid { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the SSRA Code of Conduct Agreement")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool SSRACodeofConductForm { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the Parental Code of Conduct-SSRA")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool ParentCodeofConductSSRAForm { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the Volunteer Agreement")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool VolunteerForm { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the Assumption and acceptance of rs Agreement")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool AssumptionAndAcceptanceOfRsForm { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the Medical Release Agreement")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool MedicalReleaseForm { get; set; }

        [Display(Name = "I have read and accept the terms and conditions for the Concussion Information Sheet")]
        [BooleanRequired(ErrorMessage = "You must accept the terms and conditions")]
        public bool ConcussionInfoForm { get; set; }

        [Display(Name = "Forms Complete")]
        public bool ConsentFormsOk { get; set; }

        [Display(Name = "Health Check Complete")]
        public bool HealthChkOk { get; set; }
    }
}

goSSRA.Registration/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using goSSRA.Registration.Models;
using goSSRA.Registration.ViewModel;
using goSSRA.Registration.Areas;
using System.IO;
using System.Security;
using System.Security.Permissions;
using System.Reflection;
using System.Net.Mail;
using MvcMembership;
using System.Text;


// To Due - future PDF generation
// The AllowPartiallyTrustedCallersAttribute requires the assembly to be signed with a strong name key. 
// This attribute is necessary since the control is called by either an intranet or Internet 
// Web page that should be running under restricted permissions.
//[assembly: AllowPartiallyTrustedCallers]
// To Due - future PDF generation



namespace goSSRA.Registration.Controllers
{
    [Authorize]
    public class EnrollmentController : Controller
    {

        private RegistrationDB db = new RegistrationDB();
        private readonly ISmtpClient _smtpClient;


        public EnrollmentController()
            : this(new SmtpClientProxy())
        {
        }

        public EnrollmentController(ISmtpClient smtpClient)
        {
            _smtpClient = smtpClient;
        }

        //
        // GET: /Order/
        public ActionResult Index(string sortOrder, int? sortDesc, string currentFilter, string searchString, bool excelFreindly = false)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.EnrollersNameSortParm = "Enrollers Name";
            ViewBag.FullNameSortParm = "Full Name";
            ViewBag.TitleSortParm = "Title";
            ViewBag.PaymentEmailSortParm = "Payment Email";
            ViewBag.PaidSortParm = "Paid";
            ViewBag.adminRole = false;

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }

            // toggle sort order forwards & backwards
            int _sortDesc = sortDesc ?? 0;
            _sortDesc = (_sortDesc + 1) % 2;
            ViewBag.sortDesc = _sortDesc;

            ViewBag.CurrentFilter = searchString;

            var enrollment = db.Enrollment
                .Where(e => e.EnrollmentID > 0)
                .Include(e => e.Athlete)
                .Include(e => e.Program);

            // only active program list for non-admins
            if (!User.IsInRole("Admin"))
            {
                enrollment = db.Enrollment
                    .Where(e => e.EnrollersName == User.Identity.Name)
                    .Include(e => e.Athlete)
                    .Include(e => e.Program);

                ViewBag.adminRole = false;
            }
            else
            {
                ViewBag.adminRole = true;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                enrollment = enrollment.Where(a => a.EnrollersName.ToUpper().Contains(searchString.ToUpper())
                                       || a.Athlete.FirstName.ToUpper().Contains(searchString.ToUpper())
                                       || a.Athlete.LastName.ToUpper().Contains(searchString.ToUpper())
                                       || a.Program.Title.ToUpper().Contains(searchString.ToUpper())
                                       || a.PaymentEmail.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (_sortDesc)
            {
                case 1:
                    switch (sortOrder)
                    {
                        case "Enrollers Name":
                            enrollment = enrollment.OrderBy(a => a.EnrollersName);
                            break;
                        case "Full Name":
                            enrollment = enrollment.OrderBy(a => a.Athlete.FirstName).OrderBy(a => a.Athlete.LastName);
                            break;
                        case "Title":
                            enrollment = enrollment.OrderBy(a => a.Program.Title);
                            break;
                        case "Payment Email":
                            enrollment = enrollment.OrderBy(a => a.PaymentEmail);
                            break;
                        case "Paid":
                            enrollment = enrollment.OrderBy(a => a.Paid);
                            break;
                        default:
                            enrollment = enrollment
                                .OrderBy(a => a.Athlete.FirstName).OrderBy(a => a.Athlete.LastName);
                            break;
                    }
                    break;
                default:
                    switch (sortOrder)
                    {
                        case "Enrollers Name":
                            enrollment = enrollment.OrderByDescending(a => a.EnrollersName);
                            break;
                        case "Full Name":
                            enrollment = enrollment.OrderByDescending(a => a.Athlete.FirstName).OrderByDescending(a => a.Athlete.LastName);
                            break;
                        case "Title":
                            enrollment = enrollment.OrderByDescending(a => a.Program.Title);
                            break;
                        case "Payment Email":
                            enrollment = enrollment.OrderByDescending(a => a.PaymentEmail);
                            break;
                        case "Paid":
                            enrollment = enrollment.OrderByDescending(a => a.Paid);
                            break;
                        default:
                            enrollment = enrollment
                                .OrderByDescending(a => a.Athlete.FirstName).OrderByDescending(a => a.Athlete.LastName);
                            break;
                    }
                    break;
            }
            if (excelFreindly)
            {
                return View("excelIndex", enrollment.ToList());
            }           
    
            return View(enrollment.ToList());
        }

        //
        // GET: /Order/Details/5
        public ActionResult Details(Int32 id)
        {
            Enrollment enrollment = db.Enrollment.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        //
        // GET: /Order/Create
        public ActionResult Create()
        {
            // only active program list for non-admins
            if (User.IsInRole("Admin"))
            {
                var _athletes = db.Athletes
                    .OrderBy(a => a.LastName)
                    .OrderBy(a => a.FirstName);

                ViewBag.AthleteID = new SelectList(_athletes, "AthleteID", "FullName");
            }
            else
            {
                var _athletes = db.Athletes
                    .Where(a => a.Email == User.Identity.Name);

                ViewBag.AthleteID = new SelectList(_athletes, "AthleteID", "FullName");
            }

            ViewBag.ProgramID = new SelectList(db.Programs.Where(p => p.Active == true).OrderBy(p => p.Title), "ProgramID", "Title");
            return View();
        }

        //
        // POST: /Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollment.Add(enrollment);
                db.SaveChanges();

                return RedirectToAction("Confirmation", enrollment);

                // old way to call receipt
                //return RedirectToAction("Receipt", enrollment);
            }

            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FullName", enrollment.AthleteID);
            ViewBag.ProgramID = new SelectList(db.Programs.Where(p => p.Active == true).OrderBy(p => p.Title), "ProgramID", "Title", enrollment.ProgramID);
            return View(enrollment);
        }

        //
        // GET: /Order/Edit/5
        public ActionResult Edit(Int32 id)
        {
            Enrollment enrollment = db.Enrollment.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }

            // only active program list for non-admins
            if (User.IsInRole("Admin"))
            {
                var _athletes = db.Athletes
                    .OrderBy(a => a.LastName)
                    .OrderBy(a => a.FirstName);

                ViewBag.AthleteID = new SelectList(_athletes, "AthleteID", "FullName", enrollment.AthleteID);
            }
            else
            {
                var _athletes = db.Athletes
                    .Where(a => a.Email == User.Identity.Name);

                ViewBag.AthleteID = new SelectList(_athletes, "AthleteID", "FullName", enrollment.AthleteID);
            }

            ViewBag.AthleteID = new SelectList(db.Athletes, "AthleteID", "FullName", enrollment.AthleteID);
            ViewBag.ProgramID = new SelectList(db.Programs, "ProgramID", "Title", enrollment.ProgramID);
            return View(enrollment);
        }

        //
        // POST: /Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // only active program list for non-admins
            if (User.IsInRole("Admin"))
            {
                var _athletes = db.Athletes
                    .OrderBy(a => a.LastName)
                    .OrderBy(a => a.FirstName);

                ViewBag.AthleteID = new SelectList(_athletes, "AthleteID", "FullName", enrollment.AthleteID);
            }
            else
            {

goSSRA.Registration/Views/Enrollment/Confirmation.cshtml
@model goSSRA.Registration.Models.Enrollment

@{
    ViewBag.Title = "Online Enrollment Complete";
}
<br />
<br />
<h2>Enrollment Information Submission Complete!</h2>
<br />
<br />
<div class="row">
    <div class="span12" align="center">
        <p>
            <h3>FINAL ENROLLMENT STEP:</h3>
        </p>
        <br />
        <p>
            <h3>CLICK @Html.ActionLink("HERE", "EmailReceipt", new { id = Model.EnrollmentID }, new { target = "_blank" })</h3>
        </p>
        <br />
        <p>
            and PRINT THE ENROLLMENT VERIFICATION
            **ENROLLMENT VERIFICATION MUST BE MAILED TO ADDRESS ON PRINTED VERIFICATION**
        </p>

    </div>
</div>
<br />
<div class="row" class="span12">
    <div class="span12" align="center">
        <p>
            PAYMENT CAN BE MADE ON VERIFICATION PAGE, ONCE ENROLLMENT VERIFICATION IS PRINTED<br />
            OR<br />
            PAYMENT CAN BE MAILED WITH ENROLLMENT VERIFICATION
    </div>
    </p>
</div>
<br />
<div class="row">
    <div class="span12" align="center">
        @Html.ActionLink("Back to Enrollment List", "Index")
    </div>
</div>

goSSRA.Registration/Views/Enrollment/Create.cshtml
@model goSSRA.Registration.Models.Enrollment
@{
    ViewBag.Title = "Create";
}
<br />
<br />
<h2>Create Enrollment</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend></legend>

        <div class="control-group">
            @Html.LabelFor(model => model.EnrollersName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EnrollersName)
                @Html.ValidationMessageFor(model => model.EnrollersName, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.AthleteID, "Athlete", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("AthleteID", String.Empty)
                @Html.ValidationMessageFor(model => model.AthleteID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ProgramID, "Program", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("ProgramID", String.Empty)
                @Html.ValidationMessageFor(model => model.ProgramID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.EnrollmentDate, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.EnrollmentDate)
                @Html.ValidationMessageFor(model => model.EnrollmentDate, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <p>
                    "To insure proper billing: When paying online, what email address is associated with your Paypal account (if different from the email above)?"
                </p>
            </div>
            @Html.LabelFor(model => model.PaymentEmail, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.PaymentEmail)
                @Html.ValidationMessageFor(model => model.PaymentEmail, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price, null, new { @class = "help-inline" })
            </div>
        </div>
    </fieldset>
    <br />
    <fieldset class="form-horizontal">
        <legend>Terms and Conditions</legend>
        <div class="control-group">
            @Html.LabelFor(model => model.SSRACodeofConductForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.SSRACodeofConductForm)
                @Html.ValidationMessageFor(model => model.SSRACodeofConductForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form1", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.ParentCodeofConductSSRAForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.ParentCodeofConductSSRAForm)
                @Html.ValidationMessageFor(model => model.ParentCodeofConductSSRAForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form6", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.VolunteerForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.VolunteerForm)
                @Html.ValidationMessageFor(model => model.VolunteerForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form5", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.AssumptionAndAcceptanceOfRsForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.AssumptionAndAcceptanceOfRsForm)
                @Html.ValidationMessageFor(model => model.AssumptionAndAcceptanceOfRsForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form2", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.MedicalReleaseForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.MedicalReleaseForm)
                @Html.ValidationMessageFor(model => model.MedicalReleaseForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form4", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.ConcussionInfoForm, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.ConcussionInfoForm)
                @Html.ValidationMessageFor(model => model.ConcussionInfoForm, null, new { @class = "help-inline" })
                @Html.ActionLink("details", "Form3", "Home", null, new { target = "_blank" })
            </div>
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Complete My Enrollment" class="btn" />
        </div>
    </fieldset>

}
<div>
    @Html.ActionLink("Cancel", "Index")
</div>

@section Scripts {

    <script type="text/javascript">
        $(function () {
            // retrieve  the signed on user ID to set Enrollment Name field
            $.ajax({
                url: '@Url.Action("GetUserID", "Enrollment")',
                dataType: 'json',
                type: 'POST',
                data: {},
                success: setEnrollersName,
                error: errorEnrollersName
            });

            function setEnrollersName(username) {
                $('#EnrollersName').val(username);
            }

            function errorEnrollersName(error) {
                alert("An error occured - determining user id " + error + ". Retry login.");
            }

            // retrieve  amount associated with selected program ski package
            $('#ProgramID').change(function () {
                $.ajax({
                    url: '@Url.Action("GetPrice", "Enrollment")',
                    dataType: 'json',
                    type: 'POST',
                    data: { programID: $("#ProgramID").val() },
                    success: function (data) {
                        $('#Price').val(data.Price);
                    },
                    error: function (error) {
                        alert("An error occured - determining user id " + error + ". Retry login.");
                    }
                });
            });

            function errorPrice(error) {
                alert("An error occured - determining user id " + error + ". Retry login.");
            }

            // format date - wow
            var now = new Date();
            var cMonth = now.getMonth() + 1;
            var cDay = now.getDate();
            var cYear = now.getYear() + 1900;
            var cHour = now.getHours();
            var cMinuts = now.getMinutes();
            var cSeconds = now.getSeconds();

            var TS = (cMonth <= 9 ? ('0' + cMonth) : cMonth) + '/' +
            (cDay <= 9 ? ('0' + cDay) : cDay) + '/' +
            cYear + ' ' +
            (cHour <= 0 ? ('0' + cHour) : (cHour <= 12 ? cHour : (cHour - 12))) + ':' +
            (cMinuts <= 9 ? ('0' + cMinuts) : cMinuts) + ':' +
            (cSeconds <= 9 ? '0' + cSeconds : cSeconds) + ' ' +
            (cHour <= 12 ? 'AM' : 'PM');

            // set properties for all input
            $('#EnrollersName').attr('readonly', true);
            $('#EnrollersName').css("background-color", "Gray");

            $('#EnrollmentDate').val(TS);
            $('#EnrollmentDate').attr('readonly', true);
            $('#EnrollmentDate').css("background-color", "Gray");

            $('#Price').attr('readonly', true);
            $('#Price').css("background-color", "Gray");

            $('#AthleteID').focus();
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")

}

goSSRA.Registration/Views/Enrollment/EmailConfirmed.cshtml
@{
    Layout = null;
}
<br />
<br />
<h2>Email Submited</h2>

<br />
<p><a>Email sent to : @User.Identity.Name</a></p>
<br />
<p>Check for email box for SSRA Confirmation of Enrollment. In order to complete enrollment, please sign date a copy, and 2) Mail a the signed version to the SSRA Administrator.</p>
<p>Check contacts page for mailing address.</p>
<br />
<p>Review contents and contact SSRA Register if needed.</p>
<br />
<hr />
@*<table width="100%" align="center">
    <tr>
        <td align="center">
            @Html.ActionLink("Return to My Enrollments", "Index")
        </td>
    </tr>
</table>*@

goSSRA.Registration/Views/Enrollment/EmailError.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Email Error";
}
<br />
<br />
<h2>Email Error</h2>

<p><a>There was an error submitting your email. Perhaps the logged in user could not be identified.</a></p>


<hr />
<table width="100%" align="center">
    <tr>
        <td align="center">
            @Html.ActionLink("Return to My Enrollments", "Index")
        </td>
    </tr>
</table>

goSSRA.Registration/Views/Enrollment/Receipt-.cshtml
@model goSSRA.Registration.ViewModel.Receipt

<hr />

<br />
<div align="Center">
    <a class="btn" href="@Url.Action("EmailReceipt", "Enrollment", new { id=Model.Enrollment.EnrollmentID })">Email My Confirmation to Me - Go here &raquo;</a>
</div>
<br />
<hr />

@Html.Partial("_receipt", Model)

goSSRA.Registration/Views/Enrollment/Receipt.cshtml
@model goSSRA.Registration.ViewModel.Receipt
@{
    Layout = null;
}
<br />
<style>
    /* suppress link for printing */
    @@media only print {
        a {
            display: none;
        }
    }
</style>
<div class="row">
    <a href="#" onclick="window.print(); return false;">Print</a>
    @*To Due - supress for now until more reliable SMTP host is avaliable
    <a href="@Url.Action("EmailReceipt", "Enrollment", new { id=Model.Enrollment.EnrollmentID })">Email Me</a>*@
</div>
<div class="row">
    <p><a class="btn" href="http://gossra.org/index.php?option=com_content&view=article&id=24&Itemid=32" target=" _blank">Credit Card Payment Now</a></p>
</div>
<table align="center">
    <tr>
        <td>
            <img src="@Model.ImageUrl" />
        </td>
    </tr>
</table>
<br />
<br />
<h3>
    <p align="center" cellpadding="100" cellspacing="100">
        @Html.DisplayFor(model => model.ReceiptData.HeaderInfo)
    </p>
</h3>
<br />
<table width="90%" cellpadding="3" cellspacing="3" align="center">
    <tr border="1" bgcolor="#777777" color="#ffffff">
        <td width="40%" align="center"></td>
        <td width="60%" align="center"></td>
    </tr>
    @{
        var OddColor = "#DDEEEE";
        var evenColor = "#EEFFFF";
        var Odd = OddColor;
        var Even = evenColor;
    }
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.EnrollmentDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.EnrollmentDate)
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.EnrollersName)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.EnrollersName)
        </td>
    </tr>
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.Athlete)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.Athlete.FullName)
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.Program)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.Program.Title)
        </td>
    </tr>
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.Price)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.Price)
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.Program.Description)
        </td>
        <td>
            @Html.DisplayFor(model => model.Enrollment.Program.Description)
        </td>
    </tr>
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.SSRACodeofConductForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo1 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo1
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.ParentCodeofConductSSRAForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo2 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo2
        </td>
    </tr>
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.VolunteerForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo3 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo3
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.AssumptionAndAcceptanceOfRsForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo4 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo4
        </td>
    </tr>
    <tr border="1" bgcolor="@Odd">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.MedicalReleaseForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo5 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo5
        </td>
    </tr>
    <tr border="1" bgcolor="@Even">
        <td>
            @Html.DisplayNameFor(model => model.Enrollment.ConcussionInfoForm)
        </td>
        <td>
            @{
                string AcceptTermsYesNo6 = (Model.Enrollment.AssumptionAndAcceptanceOfRsForm) ? "Yes" : "No";
            }
            @AcceptTermsYesNo6
        </td>
    </tr>
    <tr border="1" bgcolor="#777777" color="#ffffff">
        <td></td>
        <td></td>
    </tr>
</table>
<br />
<table width="80%" cellpadding="3" cellspacing="3" align="center">
    <tr>
        <td>
            @Html.DisplayFor(model => model.ReceiptData.Footer1Info)
            <br />
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.ReceiptData.Footer2Info)
            <br />
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.ReceiptData.Footer3Info)
        </td>
    </tr>
</table>
<div class="row">
    <a href="#" onclick="window.print(); return false;">Print</a>
</div>
<div class="row">
    <p><a class="btn" href="http://gossra.org/index.php?option=com_content&view=article&id=24&Itemid=32" target=" _blank">Credit Card Payment Now</a></p>
</div>