goSSRA.Registration/Controllers/VolunteerCommitmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using goSSRA.Registration.Models;

namespace goSSRA.Registration.Controllers
{
    [Authorize]
    public class VolunteerCommitmentsController : Controller
    {
        private RegistrationDB db = new RegistrationDB();

        //
        // GET: /VolunteerCommitments/
        public ActionResult Index(string sortOrder, int? sortDesc, string currentFilter, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.EventNameSortParm = "Event Name";
            ViewBag.RoleNameSortParm = "Role Name";
            ViewBag.RegistersEmailSortParm = "Registers Email";
            ViewBag.FamilyNameSortParm = "Family Name";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }

            // toggle sort order forwards & backwards
            int _sortDesc = sortDesc ?? 0;
            _sortDesc = (_sortDesc + 1) % 2;
            ViewBag.sortDesc = _sortDesc;

            ViewBag.CurrentFilter = searchString;

            var vc = db.VolunteerCommitments.Include(v => v.VolunteerEvent).Include(v => v.VolunteerRole);

            if (!String.IsNullOrEmpty(searchString))
            {
                vc = vc.Where(v => v.VolunteerEvent.EventName.ToUpper().Contains(searchString.ToUpper())
                                       || v.VolunteerRole.Role.ToUpper().Contains(searchString.ToUpper())
                                       || v.Email.ToUpper().Contains(searchString.ToUpper())
                                       || v.FamilyName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (_sortDesc)
            {
                case 1:
                    switch (sortOrder)
                    {
                        case "Role Name":
                            vc = vc.OrderBy(s => s.VolunteerRole.Role);
                            break;
                        case "Registers Email":
                            vc = vc.OrderBy(s => s.Email);
                            break;
                        case "Family Name":
                            vc = vc.OrderBy(s => s.FamilyName);
                            break;
                        case "Event Name":
                        default:
                            vc = vc.OrderBy(s => s.VolunteerEvent.EventName);
                            break;
                     }
                    break;
                default:
                    switch (sortOrder)
                    {
                        case "Role Name":
                            vc = vc.OrderByDescending(s => s.VolunteerRole.Role);
                            break;
                        case "Registers Email":
                            vc = vc.OrderByDescending(s => s.Email);
                            break;
                        case "Family Name":
                            vc = vc.OrderByDescending(s => s.FamilyName);
                            break;
                        case "Event Name":
                        default:
                            vc = vc.OrderByDescending(s => s.VolunteerEvent.EventName);
                            break;
                     }
                    break;
            }
                
                return View(vc.ToList());
        }

        //
        // GET: /VolunteerCommitments/Details/5
        public ActionResult Details(Int32 id)
        {
            VolunteerCommitments volunteercommitments = db.VolunteerCommitments.Find(id);
            if (volunteercommitments == null)
            {
                return HttpNotFound();
            }
            return View(volunteercommitments);
        }

        //
        // GET: /VolunteerCommitments/Create
        public ActionResult Create()
        {
            ViewBag.EventID = new SelectList(db.VolunteerEvents, "EventID", "EventName");
            PopulateEventDropDownList();
            ViewBag.RoleID = new SelectList(db.VolunteerRoles, "RoleID", "Role");
            return View();
        }

        //
        // POST: /VolunteerCommitments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VolunteerCommitments volunteercommitments)
        {
            if (ModelState.IsValid)
            {
                db.VolunteerCommitments.Add(volunteercommitments);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventID = new SelectList(db.VolunteerEvents, "EventID", "EventName", volunteercommitments.EventID);
            PopulateEventDropDownList(volunteercommitments.EventID);
            ViewBag.RoleID = new SelectList(db.VolunteerRoles, "RoleID", "Role", volunteercommitments.RoleID);
            return View(volunteercommitments);
        }

        //
        // GET: /VolunteerCommitments/Edit/5
        public ActionResult Edit(Int32 id)
        {
            VolunteerCommitments volunteercommitments = db.VolunteerCommitments.Find(id);
            if (volunteercommitments == null)
            {
                return HttpNotFound();
            }
            //ViewBag.EventID = new SelectList(db.VolunteerEvents, "EventID", "EventName", volunteercommitments.EventID);
            PopulateEventDropDownList(volunteercommitments.EventID);
            ViewBag.RoleID = new SelectList(db.VolunteerRoles, "RoleID", "Role", volunteercommitments.RoleID);
            return View(volunteercommitments);
        }

        //
        // POST: /VolunteerCommitments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VolunteerCommitments volunteercommitments)
        {
            if (ModelState.IsValid)
            {
                db.Entry(volunteercommitments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // ViewBag.EventID = new SelectList(db.VolunteerEvents, "EventID", "EventName", volunteercommitments.EventID);
            PopulateEventDropDownList(volunteercommitments.EventID);
            ViewBag.RoleID = new SelectList(db.VolunteerRoles, "RoleID", "Role", volunteercommitments.RoleID);
            return View(volunteercommitments);
        }
        
        // custom
        private void PopulateEventDropDownList(object selectedEvent = null)
        {
            var volunteerEventsQuery = from v in db.VolunteerEvents
                                       orderby v.Date
                                       where v.Active == true
                                       select v;

            ViewBag.EventID = new SelectList(volunteerEventsQuery, "EventID", "EventName", selectedEvent);
        }

        // custom
        private void PopulateRoleDropDownList(object selectedEvent = null)
        {
            var volunteerEventsQuery = from v in db.VolunteerEvents
                                       orderby v.Date
                                       where v.Active == true
                                       select v;

            ViewBag.EventID = new SelectList(volunteerEventsQuery, "EventID", "EventName", selectedEvent);
        }

        //
        // GET: /VolunteerCommitments/Delete/5
        public ActionResult Delete(Int32 id)
        {
            VolunteerCommitments volunteercommitments = db.VolunteerCommitments.Find(id);
            if (volunteercommitments == null)
            {
                return HttpNotFound();
            }
            return View(volunteercommitments);
        }

        //
        // POST: /VolunteerCommitments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Int32 id)
        {
            VolunteerCommitments volunteercommitments = db.VolunteerCommitments.Find(id);
            db.VolunteerCommitments.Remove(volunteercommitments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // custom
        [HttpPost]
        public ActionResult GetUserID()
        {
            return Json(User.Identity.Name);
        }

        // custom
        [HttpPost]
        public ActionResult GetRoles(string eventId)
        {
            int eventIdInt = 0;
            if (int.TryParse(eventId, out eventIdInt))
            {
                var _event = db.VolunteerEvents
                        .Where(e => e.Active == true)
                        .Where(e => e.EventID == eventIdInt)
                        .Single();

                var _roles = db.VolunteerRoles
                    .Where(r => r.Active == true)
                    .Where(r => ((r.AdminRole == _event.AdminRole) & (r.AdminRole == true)) ||
                                ((r.RaceRole == _event.RaceRole) & (r.RaceRole == true)) ||
                                ((r.OtherRole == _event.OtherRole) & (r.OtherRole == true)))
                    .Select(r => new
                    {
                        Key = r.Role,
                        Value = r.RoleID
                    }
                    );

                return Json(_roles);
            }

            return Json(false);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

goSSRA.Registration/Views/VolunteerCommitments/Create.cshtml
@model goSSRA.Registration.Models.VolunteerCommitments

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>VolunteerCommitments</legend>

        <div class="control-group">
            @Html.LabelFor(model => model.EventID, "VolunteerEvent", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("EventID", String.Empty)
                @Html.ValidationMessageFor(model => model.EventID, null, new { @class = "help-inline" })
            </div>
        </div>

        @Html.Partial("_roleIDDropDown", Model)


        <div class="control-group">
            @Html.LabelFor(model => model.Email, "Registers Email", new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.FamilyName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.FamilyName)
                @Html.ValidationMessageFor(model => model.FamilyName, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">
        $(function () {
            var SelVal = $("#EventID").val();
            getRoleIdDDlist(SelVal);
            $("#EventID").change(function () {
                SelVal = $("#EventID").val();
                getRoleIdDDlist(SelVal);
            });

            function getRoleIdDDlist(SelVal) {
                if (SelVal != 0) {
                    var url = '@Url.Action("GetRoles", "VolunteerCommitments")';
                    $.post(url, { eventID: SelVal },
                    function (_roles) {
                        var roleIDDropdown = $("#RoleID");
                        $("#RoleID").empty();
                        $("#RoleID").append('<option value="">make selection</option>');
                        for (var i = 0; i < _roles.length; i++) {
                            $("#RoleID").append('<option value="' + _roles[i].Value + '">' + _roles[i].Key + '</option>');
                        }
                    });
                    $("#RoleID").disabled = false;
                }
                else {
                    $("#RoleID").empty();
                    $("#RoleID").append('<option value=""></option>');
                    $("#RoleID").disabled = true;
                }
            };

           // retrieve  the signed on user ID to set Enrollment Name field
           $.ajax({
               url: '@Url.Action("GetUserID", "Enrollment")',
               dataType: 'json',
               type: 'POST',
               data: { },
               success: function (username) {
                   $('#Email').val(username);

                   // set properties for all input
                   $('#Email').attr('readonly', true);
                   $('#Email').css("background-color", "Gray");
               },
               error: function (error) {
                   alert("An error occured - determining user id " + error + ". Retry login.");
               }
           });
       });
</script>
}

goSSRA.Registration/Views/VolunteerCommitments/Delete.cshtml
@model goSSRA.Registration.Models.VolunteerCommitments

@{
    ViewBag.Title = "Delete";
}
<br />
<br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>VolunteerCommitments</legend>

	<dl>
		<dt>
			@Html.DisplayNameFor(model => model.VolunteerEvent.EventName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.VolunteerEvent.EventName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.VolunteerRole.Role)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.VolunteerRole.Role)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Email)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Email)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.FamilyName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.FamilyName)
		</dd>

	</dl>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

goSSRA.Registration/Views/VolunteerCommitments/Details.cshtml
@model goSSRA.Registration.Models.VolunteerCommitments

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<h2>Details</h2>

<fieldset>
	<legend>VolunteerCommitments</legend>
	<dl>
		<dt>
			@Html.DisplayNameFor(model => model.VolunteerEvent.EventName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.VolunteerEvent.EventName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.VolunteerRole.Role)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.VolunteerRole.Role)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Email)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Email)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.FamilyName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.FamilyName)
		</dd>

	</dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.CommitmentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

goSSRA.Registration/Views/VolunteerCommitments/Edit.cshtml
@model goSSRA.Registration.Models.VolunteerCommitments

@{
    ViewBag.Title = "Edit";
}
<br />
<br />
<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>VolunteerCommitments</legend>

        @Html.HiddenFor(model => model.CommitmentID)

        <div class="control-group">
            @Html.LabelFor(model => model.EventID, "Event", new { @class = "control-label" })
			<div class="controls">
				@Html.DropDownList("EventID", String.Empty)
				@Html.ValidationMessageFor(model => model.EventID, null, new { @class = "help-inline" })
			</div>
		</div>

        <div class="control-group">
            @Html.LabelFor(model => model.RoleID, "Preferred Role", new { @class = "control-label" })
			<div class="controls">
				@Html.DropDownList("RoleID", String.Empty)
				@Html.ValidationMessageFor(model => model.RoleID, null, new { @class = "help-inline" })
			</div>
		</div>

        <div class="control-group">
            @Html.LabelFor(model => model.Email, "Registers Email", new { @class = "control-label" })
			<div class="controls">
                @Html.EditorFor(model => model.Email)
				@Html.ValidationMessageFor(model => model.Email, null, new { @class = "help-inline" })
			</div>
		</div>

        <div class="control-group">
            @Html.LabelFor(model => model.FamilyName, new { @class = "control-label" })
			<div class="controls">
				@Html.EditorFor(model => model.FamilyName)
				@Html.ValidationMessageFor(model => model.FamilyName, null, new { @class = "help-inline" })
			</div>
		</div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
     $(function () {
         var SelVal = $("#EventID").val();
         getRoleIdDDlist(SelVal);
         $("#EventID").change(function () {
             SelVal = $("#EventID").val();
             getRoleIdDDlist(SelVal);
         });

         function getRoleIdDDlist(SelVal) {
             if (SelVal != 0) {
                 var url = '@Url.Action("GetRoles", "VolunteerCommitments")';
                 $.post(url, { eventID: SelVal },
                 function (_roles) {
                     var roleIDDropdown = $("#RoleID");
                     $("#RoleID").empty();
                     $("#RoleID").append('<option value="">make selection</option>');
                     for (var i = 0; i < _roles.length; i++) {
                         $("#RoleID").append('<option value="' + _roles[i].Value + '">' + _roles[i].Key + '</option>');
                     }
                 });
                 $("#RoleID").disabled = false;
             }
             else {
                 $("#RoleID").empty();
                 $("#RoleID").append('<option value=""></option>');
                 $("#RoleID").disabled = true;
             }
         };

        // retrieve  the signed on user ID to set Enrollment Name field
        $.ajax({
            url: '@Url.Action("GetUserID", "Enrollment")',
            dataType: 'json',
            type: 'POST',
            data: { },
            success: function (username) {
                $('#Email').val(username);

                // set properties for all input
                $('#Email').attr('readonly', true);
                $('#Email').css("background-color", "Gray");
            },
            error: function (error) {
                alert("An error occured - determining user id " + error + ". Retry login.");
            }
        });
    });
</script>
}

goSSRA.Registration/Views/VolunteerCommitments/Index.cshtml
@model IEnumerable<goSSRA.Registration.Models.VolunteerCommitments>

@{
    ViewBag.Title = "SSRA Events";
}
<br />
<br />
<div style="text-align: center">
    <h2>SSRA Events</h2>
    <br /><p>
        Event Sign Up @Html.ActionLink("here", "Create")
    </p><br />
    <hr>
</div>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="span4">
            <h4>Current Event Sign Up</h4>
        </div>
        <div class="span4">

        </div>
        <div class="span4">
            <p>
                Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                <input type="submit" value="Search" class="btn" />
            </p>
        </div>
    </div>
}
@{
    var TopColor = "#EEEEDD";
    var OddColor = "#FAFAF4";
    var evenColor = "#FFFFFA";
    var Odd = OddColor;
}
<table class="table">
    <tr border="1" bgcolor="@TopColor">
        <th>
            @Html.ActionLink("Event Name", "Index", new { sortOrder = ViewBag.EventNameSortParm, sortDesc = ViewBag.sortDesc, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.VolunteerEvent.EventName)*@
        </th>
        <th>
            @Html.ActionLink("Role Name", "Index", new { sortOrder = ViewBag.RoleNameSortParm, sortDesc = ViewBag.sortDesc, currentFilter = ViewBag.CurrentFilter })

            @*@Html.DisplayNameFor(model => model.VolunteerRole.Role)*@
        </th>
        <th>
            @Html.ActionLink("Registers Email", "Index", new { sortOrder = ViewBag.RegistersEmailSortParm, sortDesc = ViewBag.sortDesc, currentFilter = ViewBag.CurrentFilter })

            @*@Html.DisplayNameFor(model => model.Email)*@
        </th>
        <th>
            @Html.ActionLink("Family Name", "Index", new { sortOrder = ViewBag.FamilyNameSortParm, sortDesc = ViewBag.sortDesc, currentFilter = ViewBag.CurrentFilter })

            @*@Html.DisplayNameFor(model => model.FamilyName)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr border="1" bgcolor="@Odd">
    <td>
        @Html.DisplayFor(modelItem => item.VolunteerEvent.EventName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.VolunteerRole.Role)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FamilyName)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.CommitmentID }) |
        @*@Html.ActionLink("Details", "Details", new { id = item.CommitmentID }) |*@
        @Html.ActionLink("Delete", "Delete", new { id = item.CommitmentID })
    </td>
</tr>
        if (Odd == OddColor)
        {
            Odd = evenColor;
        }
        else
        {
            Odd = OddColor;
        }
    }

</table>

goSSRA.Registration/Views/VolunteerCommitments/_roleIDDropDown.cshtml
@model goSSRA.Registration.Models.VolunteerCommitments

<div class="control-group" id="divRoleID">
    @Html.LabelFor(model => model.RoleID, "VolunteerRole", new { @class = "control-label" })
    <div class="controls">
        @Html.DropDownList("RoleID", String.Empty)
        @Html.ValidationMessageFor(model => model.RoleID, null, new { @class = "help-inline" })
    </div>
</div>